version: '3'

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: >
      bash -c "./wait-for-it.sh db:3306 -t 15
      && python manage.py makemigrations
      && python manage.py migrate
      && mysql -u root -p door_access_control_system < test.sql
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/door_access_control_system/
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_USER: 'admin'
      MYSQL_DATABASE: 'door_access_control_system'
      MYSQL_PASSWORD: 'password'
    ports:
      - "3306:3306"
    expose:
      - "3306"